export const firstRegistrations = [
	{ name: '2025', id: 2025 },
	{ name: '2024', id: 2024 },
	{ name: '2023', id: 2023 },
	{ name: '2022', id: 2022 },
	{ name: '2021', id: 2021 },
	{ name: '2020', id: 2020 },
	{ name: '2019', id: 2019 },
	{ name: '2018', id: 2018 },
	{ name: '2017', id: 2017 },
	{ name: '2016', id: 2016 },
] as const

export const mileages = [
	{ name: '50 km', id: 50 },
	{ name: '5,000 km', id: 5000 },
	{ name: '10,000 km', id: 10000 },
	{ name: '20,000 km', id: 20000 },
	{ name: '30,000 km', id: 30000 },
	{ name: '40,000 km', id: 40000 },
	{ name: '50,000 km', id: 50000 },
	{ name: '60,000 km', id: 60000 },
	{ name: '70,000 km', id: 70000 },
	{ name: '80,000 km', id: 80000 },
	{ name: '90,000 km', id: 90000 },
	{ name: '100,000 km', id: 100000 },
	{ name: '125,000 km', id: 125000 },
	{ name: '150,000 km', id: 150000 },
	{ name: '175,000 km', id: 175000 },
	{ name: '200,000 km', id: 200000 },
] as const

export const originCountry = [
	{ name: 'Austria', id: 'austria' },
	{ name: 'Belgium', id: 'belgium' },
	{ name: 'Bulgaria', id: 'bulgaria' },
	{ name: 'China', id: 'china' },
	{ name: 'Croatia', id: 'croatia' },
	{ name: 'Czech Republic', id: 'czech_republic' },
	{ name: 'Denmark', id: 'denmark' },
	{ name: 'Estonia', id: 'estonia' },
	{ name: 'Finland', id: 'finland' },
	{ name: 'France', id: 'france' },
	{ name: 'Germany', id: 'germany' },
	{ name: 'Hungary', id: 'hungary' },
	{ name: 'Japan', id: 'japan' },
	{ name: 'Italy', id: 'italy' },
	{ name: 'Latvia', id: 'latvia' },
	{ name: 'Liechtenstein', id: 'liechtenstein' },
	{ name: 'Lithuania', id: 'lithuania' },
	{ name: 'Luxembourg', id: 'luxembourg' },
	{ name: 'Netherlands', id: 'netherlands' },
	{ name: 'Poland', id: 'poland' },
	{ name: 'Portugal', id: 'portugal' },
	{ name: 'Romania', id: 'romania' },
	{ name: 'Russia', id: 'russia' },
	{ name: 'Slovakia', id: 'slovakia' },
	{ name: 'Slovenia', id: 'slovenia' },
	{ name: 'Spain', id: 'spain' },
	{ name: 'Sweden', id: 'sweden' },
	{ name: 'United Kingdom', id: 'united_kingdom' },
	{ name: 'United States', id: 'united_states' },
] as const

export const currentPrice = [
	{ name: '1,000', id: 1000 },
	{ name: '2,000', id: 2000 },
	{ name: '3,000', id: 3000 },
	{ name: '4,000', id: 4000 },
	{ name: '5,000', id: 5000 },
	{ name: '6,000', id: 6000 },
	{ name: '7,000', id: 7000 },
	{ name: '8,000', id: 8000 },
	{ name: '9,000', id: 9000 },
	{ name: '10,000', id: 10000 },
	{ name: '11,000', id: 11000 },
	{ name: '12,000', id: 12000 },
	{ name: '13,000', id: 13000 },
	{ name: '14,000', id: 14000 },
	{ name: '15,000', id: 15000 },
	{ name: '16,000', id: 16000 },
	{ name: '17,000', id: 17000 },
	{ name: '18,000', id: 18000 },
	{ name: '19,000', id: 19000 },
	{ name: '20,000', id: 20000 },
	{ name: '25,000', id: 25000 },
	{ name: '30,000', id: 30000 },
	{ name: '35,000', id: 35000 },
	{ name: '40,000', id: 40000 },
	{ name: '45,000', id: 45000 },
	{ name: '50,000', id: 50000 },
] as const

export const power = {
	hp: [
		{ name: '50 hp', id: 50 },
		{ name: '60 hp', id: 60 },
		{ name: '70 hp', id: 70 },
		{ name: '80 hp', id: 80 },
		{ name: '90 hp', id: 90 },
		{ name: '100 hp', id: 100 },
		{ name: '110 hp', id: 110 },
		{ name: '120 hp', id: 120 },
		{ name: '130 hp', id: 130 },
		{ name: '140 hp', id: 140 },
		{ name: '150 hp', id: 150 },
		{ name: '175 hp', id: 175 },
		{ name: '200 hp', id: 200 },
		{ name: '225 hp', id: 225 },
		{ name: '250 hp', id: 250 },
		{ name: '300 hp', id: 300 },
		{ name: '350 hp', id: 350 },
		{ name: '400 hp', id: 400 },
		{ name: '450 hp', id: 450 },
		{ name: '500 hp', id: 500 },
	],
	kW: [
		{ name: '36 kW', id: 36 },
		{ name: '44 kW', id: 44 },
		{ name: '51 kW', id: 51 },
		{ name: '58 kW', id: 58 },
		{ name: '66 kW', id: 66 },
		{ name: '73 kW', id: 73 },
		{ name: '80 kW', id: 80 },
		{ name: '88 kW', id: 88 },
		{ name: '95 kW', id: 95 },
		{ name: '103 kW', id: 103 },
		{ name: '110 kW', id: 110 },
		{ name: '128 kW', id: 128 },
		{ name: '147 kW', id: 147 },
		{ name: '165 kW', id: 165 },
		{ name: '183 kW', id: 183 },
		{ name: '220 kW', id: 220 },
		{ name: '257 kW', id: 257 },
		{ name: '294 kW', id: 294 },
		{ name: '331 kW', id: 331 },
	],
} as const

export const colors = [
	{ name: 'Beige', id: 'beige', color: 'bg-orange-300' },
	{ name: 'Black', id: 'black', color: 'bg-black' },
	{ name: 'Burgundy', id: 'burgundy', color: 'bg-red-800' },
	{ name: 'Purple', id: 'purple', color: 'bg-purple-600' },
	{ name: 'Green', id: 'green', color: 'bg-green-500' },
	{ name: 'Red', id: 'red', color: 'bg-red-500' },
	{ name: 'Blue', id: 'blue', color: 'bg-blue-600' },
	{ name: 'Grey', id: 'grey', color: 'bg-gray-500' },
	{ name: 'White', id: 'white', color: 'bg-white' },
	{ name: 'Brown', id: 'brown', color: 'bg-amber-800' },
	{ name: 'Orange', id: 'orange', color: 'bg-orange-400' },
	{ name: 'Yellow', id: 'yellow', color: 'bg-yellow-400' },
] as const

export const country = [
	{ name: 'Albania', id: 'albania' },
	{ name: 'Algeria', id: 'algeria' },
	{ name: 'Andorra', id: 'andorra' },
	{ name: 'Armenia', id: 'armenia' },
	{ name: 'Austria', id: 'austria' },
	{ name: 'Azerbaijan', id: 'azerbaijan' },
	{ name: 'Belgium', id: 'belgium' },
	{ name: 'Bosnia Herzegowina', id: 'bosnia_herzegowina' },
	{ name: 'British Virgin Islands', id: 'british_virgin_islands' },
	{ name: 'Bulgaria', id: 'bulgaria' },
	{ name: 'Canary Islands', id: 'canary_islands' },
	{ name: 'Cape Verde', id: 'cape_verde' },
	{ name: 'Croatia', id: 'croatia' },
	{ name: 'Cyprus', id: 'cyprus' },
	{ name: 'Czech republic', id: 'czech_republic' },
	{ name: 'Denmark', id: 'denmark' },
	{ name: 'Estonia', id: 'estonia' },
	{ name: 'Finland', id: 'finland' },
	{ name: 'France', id: 'france' },
	{ name: 'Georgia', id: 'georgia' },
	{ name: 'Germany', id: 'germany' },
	{ name: 'Ghana', id: 'ghana' },
	{ name: 'Greece', id: 'greece' },
	{ name: 'Hungary', id: 'hungary' },
	{ name: 'Iceland', id: 'iceland' },
	{ name: 'Ireland', id: 'ireland' },
	{ name: 'Israel', id: 'israel' },
	{ name: 'Italy', id: 'italy' },
	{ name: 'Jordan', id: 'jordan' },
	{ name: 'Latvia', id: 'latvia' },
	{ name: 'Liechtenstein', id: 'liechtenstein' },
	{ name: 'Lithuania', id: 'lithuania' },
	{ name: 'Luxembourg', id: 'luxembourg' },
	{ name: 'Macedonia', id: 'macedonia' },
	{ name: 'Madagascar', id: 'madagascar' },
	{ name: 'Malta', id: 'malta' },
	{ name: 'Morocco', id: 'morocco' },
	{ name: 'Moldova', id: 'moldova' },
	{ name: 'Montenegro', id: 'montenegro' },
	{ name: 'Netherlands', id: 'netherlands' },
	{ name: 'Norway', id: 'norway' },
	{ name: 'Poland', id: 'poland' },
	{ name: 'Portugal', id: 'portugal' },
	{ name: 'Republic of Kosovo', id: 'republic_of_kosovo' },
	{ name: 'Romania', id: 'romania' },
	{ name: 'San Marino', id: 'san_marino' },
	{ name: 'Serbia', id: 'serbia' },
	{ name: 'Slovakia', id: 'slovakia' },
	{ name: 'Slovenia', id: 'slovenia' },
	{ name: 'Spain', id: 'spain' },
	{ name: 'Sweden', id: 'sweden' },
	{ name: 'Switzerland', id: 'switzerland' },
	{ name: 'Tunisia', id: 'tunisia' },
	{ name: 'Turkey', id: 'turkey' },
	{ name: 'United Kingdom', id: 'united_kingdom' },
] as const

// export const businessType = [
// 	{ name: 'Car Treder / Dealer', id: 'trader_dealer' },
// 	{ name: 'Fleet owner', id: 'fleet_owner' },
// 	{ name: 'Leasing Company', id: 'leasing_company' },
// 	{ name: 'Manufacturer', id: 'manufacturer' },
// 	{ name: 'Rental company', id: 'rental_company' },
// ] as const

export const businessDescription = [
	{
		name: 'Trader',
		description:
			'I trade all kinds of brands from a small office, sometimes with a small parking lot.',
		id: 'trader',
	},
	{
		name: 'Broker',
		description:
			"I act as a car sales broker from my home office. I don't have a showroom or parking lot.",
		id: 'broker',
	},
	{
		name: 'Independent dealer',
		description:
			'I have a showroom, website, parking lot and office with employee(s).',
		id: 'independent',
	},
	{
		name: 'Franchised dealer',
		description:
			'I represent up to 5 brands, with multiple entities, showrooms and service facilities.',
		id: 'franchised',
	},
	{
		name: 'Dealer group',
		description:
			'I represent more than 5 brands, with multiple entities and showrooms and service facilities.',
		id: 'dealer',
	},
]

// Sorting
export const sortingOptions = [
	{ name: 'Most recent on top', id: 'most_recent' },
	{ name: 'A - Z', id: 'a_to_z' },
	{ name: 'Z - A', id: 'z_to_a' },
	{ name: 'Registration date - Ascending', id: 'registration_date_asc' },
	{ name: 'Registration date - Descending', id: 'registration_date_desc' },
	{ name: 'Mileage - Ascending', id: 'mileage_asc' },
	{ name: 'Mileage - Descending', id: 'mileage_desc' },
	{ name: 'Price - Ascending', id: 'price_asc' },
	{ name: 'Price - Descending', id: 'price_desc' },
] as const

export const sortingOptionsOutcome = [
	{ name: 'A - Z', id: 'a_to_z' },
	{ name: 'Z - A', id: 'z_to_a' },
	{ name: 'Final price - Ascending', id: 'price_asc' },
	{ name: 'Final price - Descending', id: 'price_desc' },
] as const

export const sortingOptionsActive = [
	{ name: 'Time left - Ascending', id: 'end_date_asc' },
	{ name: 'Time left - Descending', id: 'end_date_desc' },
	{ name: 'A - Z', id: 'a_to_z' },
	{ name: 'Z - A', id: 'z_to_a' },
	{ name: 'Current price - Ascending', id: 'price_asc' },
	{ name: 'Current price - Descending', id: 'price_desc' },
] as const
